# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Binary search - Larger or equal to
#' 
#' @description Find index of first value larger or equal to x in a sorted array
#' 
#' @keywords internal
#' @param v - sorted vector instance
#' @param data - value to search
#' @return index of first value larger or equal than data, -1 otherwise
binary_search_larger_equal <- function(v, data) {
    .Call(`_icmstate_binary_search_larger_equal`, v, data)
}

#' Binary search - Larger 
#' 
#' @description Find index of first value larger than x in a sorted array
#' 
#' @keywords internal
#' @param v - sorted vector instance
#' @param data - value to search
#' @return index of first value larger than data -1, -1 otherwise
binary_search_larger <- function(v, data) {
    .Call(`_icmstate_binary_search_larger`, v, data)
}

